"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OSWAP_OracleUnity = exports.OSWAP_OracleSigned = exports.OSWAP_OracleSetYourOwnPrice = exports.OSWAP_OracleConstantLimited = exports.OSWAP_OracleConstant = exports.OSWAP_OracleChainlinkPriceGuardFiatBinance = exports.OSWAP_OracleChainlinkPriceGuardFiatAvalanche = exports.OSWAP_OracleChainlinkPriceGuardBinance = exports.OSWAP_OracleChainlinkLimited = exports.OSWAP_OracleChainlinkV1Generic = exports.OSWAP_OracleChainlinkPriceGuardGeneric = exports.OSWAP_OracleChainlinkPriceGuardFiatGeneric = exports.OSWAP_OracleChainlinkLimitedGeneric = exports.OSWAP_OracleChainlinkGeneric = exports.OSWAP_OracleChainlinkFiatGeneric = exports.OSWAP_OracleChainlinkFiatBinance = exports.OSWAP_OracleChainlinkFiatAvalanche = exports.OSWAP_OracleChainlinkFiat = exports.OSWAP_OracleChainlinkBinance = exports.OSWAP_OracleChainlink = exports.OSWAP_OracleChained = void 0;
var OSWAP_OracleChained_1 = require("./OSWAP_OracleChained");
Object.defineProperty(exports, "OSWAP_OracleChained", { enumerable: true, get: function () { return OSWAP_OracleChained_1.OSWAP_OracleChained; } });
var OSWAP_OracleChainlink_1 = require("./OSWAP_OracleChainlink");
Object.defineProperty(exports, "OSWAP_OracleChainlink", { enumerable: true, get: function () { return OSWAP_OracleChainlink_1.OSWAP_OracleChainlink; } });
var OSWAP_OracleChainlinkBinance_1 = require("./OSWAP_OracleChainlinkBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkBinance_1.OSWAP_OracleChainlinkBinance; } });
var OSWAP_OracleChainlinkFiat_1 = require("./OSWAP_OracleChainlinkFiat");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiat", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiat_1.OSWAP_OracleChainlinkFiat; } });
var OSWAP_OracleChainlinkFiatAvalanche_1 = require("./OSWAP_OracleChainlinkFiatAvalanche");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiatAvalanche", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiatAvalanche_1.OSWAP_OracleChainlinkFiatAvalanche; } });
var OSWAP_OracleChainlinkFiatBinance_1 = require("./OSWAP_OracleChainlinkFiatBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiatBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiatBinance_1.OSWAP_OracleChainlinkFiatBinance; } });
var OSWAP_OracleChainlinkFiatGeneric_1 = require("./OSWAP_OracleChainlinkFiatGeneric");
Object.defineProperty(exports, "OSWAP_OracleChainlinkFiatGeneric", { enumerable: true, get: function () { return OSWAP_OracleChainlinkFiatGeneric_1.OSWAP_OracleChainlinkFiatGeneric; } });
var OSWAP_OracleChainlinkGeneric_1 = require("./OSWAP_OracleChainlinkGeneric");
Object.defineProperty(exports, "OSWAP_OracleChainlinkGeneric", { enumerable: true, get: function () { return OSWAP_OracleChainlinkGeneric_1.OSWAP_OracleChainlinkGeneric; } });
var OSWAP_OracleChainlinkLimitedGeneric_1 = require("./OSWAP_OracleChainlinkLimitedGeneric");
Object.defineProperty(exports, "OSWAP_OracleChainlinkLimitedGeneric", { enumerable: true, get: function () { return OSWAP_OracleChainlinkLimitedGeneric_1.OSWAP_OracleChainlinkLimitedGeneric; } });
var OSWAP_OracleChainlinkPriceGuardFiatGeneric_1 = require("./OSWAP_OracleChainlinkPriceGuardFiatGeneric");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardFiatGeneric", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardFiatGeneric_1.OSWAP_OracleChainlinkPriceGuardFiatGeneric; } });
var OSWAP_OracleChainlinkPriceGuardGeneric_1 = require("./OSWAP_OracleChainlinkPriceGuardGeneric");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardGeneric", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardGeneric_1.OSWAP_OracleChainlinkPriceGuardGeneric; } });
var OSWAP_OracleChainlinkV1Generic_1 = require("./OSWAP_OracleChainlinkV1Generic");
Object.defineProperty(exports, "OSWAP_OracleChainlinkV1Generic", { enumerable: true, get: function () { return OSWAP_OracleChainlinkV1Generic_1.OSWAP_OracleChainlinkV1Generic; } });
var OSWAP_OracleChainlinkLimited_1 = require("./OSWAP_OracleChainlinkLimited");
Object.defineProperty(exports, "OSWAP_OracleChainlinkLimited", { enumerable: true, get: function () { return OSWAP_OracleChainlinkLimited_1.OSWAP_OracleChainlinkLimited; } });
var OSWAP_OracleChainlinkPriceGuardBinance_1 = require("./OSWAP_OracleChainlinkPriceGuardBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardBinance_1.OSWAP_OracleChainlinkPriceGuardBinance; } });
var OSWAP_OracleChainlinkPriceGuardFiatAvalanche_1 = require("./OSWAP_OracleChainlinkPriceGuardFiatAvalanche");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardFiatAvalanche", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardFiatAvalanche_1.OSWAP_OracleChainlinkPriceGuardFiatAvalanche; } });
var OSWAP_OracleChainlinkPriceGuardFiatBinance_1 = require("./OSWAP_OracleChainlinkPriceGuardFiatBinance");
Object.defineProperty(exports, "OSWAP_OracleChainlinkPriceGuardFiatBinance", { enumerable: true, get: function () { return OSWAP_OracleChainlinkPriceGuardFiatBinance_1.OSWAP_OracleChainlinkPriceGuardFiatBinance; } });
var OSWAP_OracleConstant_1 = require("./OSWAP_OracleConstant");
Object.defineProperty(exports, "OSWAP_OracleConstant", { enumerable: true, get: function () { return OSWAP_OracleConstant_1.OSWAP_OracleConstant; } });
var OSWAP_OracleConstantLimited_1 = require("./OSWAP_OracleConstantLimited");
Object.defineProperty(exports, "OSWAP_OracleConstantLimited", { enumerable: true, get: function () { return OSWAP_OracleConstantLimited_1.OSWAP_OracleConstantLimited; } });
var OSWAP_OracleSetYourOwnPrice_1 = require("./OSWAP_OracleSetYourOwnPrice");
Object.defineProperty(exports, "OSWAP_OracleSetYourOwnPrice", { enumerable: true, get: function () { return OSWAP_OracleSetYourOwnPrice_1.OSWAP_OracleSetYourOwnPrice; } });
var OSWAP_OracleSigned_1 = require("./OSWAP_OracleSigned");
Object.defineProperty(exports, "OSWAP_OracleSigned", { enumerable: true, get: function () { return OSWAP_OracleSigned_1.OSWAP_OracleSigned; } });
var OSWAP_OracleUnity_1 = require("./OSWAP_OracleUnity");
Object.defineProperty(exports, "OSWAP_OracleUnity", { enumerable: true, get: function () { return OSWAP_OracleUnity_1.OSWAP_OracleUnity; } });
